### ISSUE TITLE
{{extends}} syntax does not available

### ISSUE THREAD

**Issue by feelinc** [CloudyKit/jet#64]
This is my first time trying Jet.

**Layout and template created :**
```
<!-- file: "views/layouts/application.jet" -->
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    {{yield body()}}
  </body>
</html>

<!-- file: "views/home.jet" -->
{{extends "layouts/application.jet"}}
{{block body()}}
  <main>
    This content will be yielded in the layout above.
  </main>
{{end}}
```

**Echo middleware :**
```
package middleware

import (
	"fmt"
	"io"

	"github.com/CloudyKit/jet"
	"github.com/labstack/echo"
)

// Template type.
type Template struct {
	View *jet.Set
}

// Render satisfies the Echo.Renderer interface.
func (r *Template) Render(w io.Writer, name string, data interface{}, c echo.Context) error {
	t, err := r.View.GetTemplate(name)
	if err != nil {
		panic(fmt.Errorf("Fatal error template file: %s", err))
	}
	vars, ok := data.(jet.VarMap)
	if !ok { // data passed wasn't a var map
		vars = jet.VarMap{}
	}
	err = t.Execute(w, vars, nil)
	if err != nil {
		// render an error response?
		// log the error?
		// up to you
	}
	return nil
}
```
**Main package :**
```
package main

import (
	"path/filepath"

	"github.com/CloudyKit/jet"
	"github.com/facebookgo/grace/gracehttp"
	"github.com/my/project/app/controllers"
	middlewares "github.com/my/project/app/middleware"
	"github.com/labstack/echo"
)

func main() {
	// Echo instance
	e := echo.New()

	// Template middleware
	view := jet.NewHTMLSet(filepath.Join("./app", "views"))
	view.SetDevelopmentMode(true)
	e.Renderer = &middlewares.Template{View: view}

	// Authentication
	e.GET("/login", controllers.LoginIndex)

	// Start server
	e.Server.Addr = ":1323"
	e.Logger.Fatal(gracehttp.Serve(e.Server))
}
```

**Endpoint handler :**
```
package controllers

import (
	"github.com/CloudyKit/jet"
	"github.com/labstack/echo"
)

// LoginIndex handle login view.
func LoginIndex(c echo.Context) error {
	vars := jet.VarMap{}
	vars.Set("test", true)
	return c.Render(200, "welcome.jet", vars)
}
```

**Result :**
```
template: welcome.jet:2: unexpected token <extends> on operand goroutine 57 [running]:
github.com/my/project/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x9f5278, 0x1000, 0x15470000, 0xc60fe0, 0xc420276150)
    /home/my-user/.gvm/pkgsets/go1.8.3/global/src/github.com/my/project/vendor/github.com/labstack/echo/middleware/recover.go:75 +0x134
panic(0x9382c0, 0xc42027a9d0)
    /home/my-user/.gvm/gos/go1.8.3/src/runtime/panic.go:489 +0x2cf
github.com/my/project/app/middleware.(*Template).Render(0xc42000ebf8, 0xc51fe0, 0xc420276d90, 0x9d8412, 0xb, 0x970040, 0xc42021aed0, 0xc60fe0, 0xc420276150, 0xc42027a93a, ...)
    /home/my-user/.gvm/pkgsets/go1.8.3/global/src/github.com/my/project/app/middleware/template.go:20 +0x198
github.com/my/project/vendor/github.com/labstack/echo.(*context).Render(0xc420276150, 0xc8, 0x9d8412, 0xb, 0x970040, 0xc42021aed0, 0xc87f90, 0x1c)
    /home/my-user/.gvm/pkgsets/go1.8.3/global/src/github.com/my/project/vendor/github.com/labstack/echo/context.go:369 +0xcb
github.com/my/project/app/controllers.LoginIndex(0xc60fe0, 0xc420276150, 0xc42028a748, 0xc42021aea0)
    /home/my-user/.gvm/pkgsets/go1.8.3/global/src/github.com/my/project/app/controllers/auth.go:12
```

Are there something missing in my implementation?

**Comment by feelinc** [comment]
**Glide :**
```
package: github.com/my/project
import:
- package: github.com/CloudyKit/jet
  version: ^2.1.1
```

**Comment by jhsx** [comment]
Hi, @feelinc there is an implementation detail or bug maybe, that the extends need to be the first statement on the file.
You can fix this error by moving the comment to after the extends.
```
{{extends "layouts/application.jet"}}
<!-- file: "views/home.jet" -->
{{block body()}}
  <main>
    This content will be yielded in the layout above.
  </main>
{{end}}

```

**Comment by feelinc** [comment]
Thanks, it's working now.
